export var hostUrl: string = 'https://api-services.dpolg.app';

export var dpolgAppConfig: any = {
	appDescription: 'DPolG',
	appId: 'de.jungepolizei.dpolg',
	appName: 'DPolG',
	appPages: [],
	appSlogan: 'DPolG',
	defaultLanguage: 'de',
	environments: {
		api: {
			local: 'https://api-services.dpolg.local/api',
			production: 'https://api-services.dpolg.app/api',
			staging: 'https://staging.api-services.dpolg.app/api',
			testing: 'https://testing.api-services.dpolg.app/api',
		},
		app: {
			local: 'https://web.dpolg.local',
			production: 'https://web.dpolg.app',
			staging: 'https://staging.web.dpolg.app',
			testing: 'https://testing.web.dpolg.app',
		},
	},
	launcherSettings: {
		links: [
			{
				name: 'catalog_of_facts',
				photo: './assets/img/dpolg/card_img/tatbestandkatalog.png',
				uid: 'catalog_of_facts',
				url: '/pages/catalog_of_facts',
				usePhotoAsBackground: true,
			},
			{
				name: 'shop',
				photo: './assets/img/dpolg/card_img/shop.png',
				uid: 'shop',
				url: 'https://www.dpolg-markt-select.de/',
				usePhotoAsBackground: true,
			},
			{
				name: 'hazardous_substances',
				photo: './assets/img/dpolg/card_img/gefahrstoffe.png',
				uid: 'hazardous_substances',
				url: '/pages/hazardous_substances',
				usePhotoAsBackground: true,
			},
			{
				name: 'abbreviations',
				photo: './assets/img/dpolg/card_img/abkuerzungen.png',
				uid: 'abbreviations',
				url: '/pages/abbreviations',
				usePhotoAsBackground: true,
			},
			{
				name: 'medical_care',
				photo: './assets/img/dpolg/card_img/heilfuersorge.png',
				uid: 'medical_care',
				url: '/pages/health_care',
				usePhotoAsBackground: true,
			},
			{
				name: 'gun_control_low',
				photo: './assets/img/dpolg/card_img/waffenuebersicht.png',
				uid: 'gun_control_low',
				url: '/pages/gun_control_low',
				usePhotoAsBackground: true,
			},
			{
				name: 'narcotics',
				photo: './assets/img/dpolg/card_img/betaeubungsmittel.png',
				uid: 'narcotics',
				url: '/pages/narcotics',
				usePhotoAsBackground: true,
			},
			{
				name: 'licence_plates',
				photo: './assets/img/dpolg/card_img/kfz_kennzeichen.png',
				uid: 'licence_plates',
				url: '/pages/licence_plates',
				usePhotoAsBackground: true,
			},
			{
				name: 'traffic_signs',
				photo: './assets/img/dpolg/card_img/verkehrszeichen.png',
				uid: 'traffic_signs',
				url: '/pages/traffic_signs',
				usePhotoAsBackground: true,
			},
			// {
			// 	name: 'youth_protection',
			// 	photo: './assets/img/dpolg/card_img/jugendschutz.png',
			// 	uid: 'youth_protection',
			// 	url: '/pages/youth_protection',
			// 	usePhotoAsBackground: true,
			// },
			{
				name: 'youth_protection',
				photo: './assets/img/dpolg/card_img/jugendschutz.png',
				uid: 'youth_protection',
				url: 'https://www.gesetze-im-internet.de/juschg/JuSchG.pdf',
				usePhotoAsBackground: true,
			},
			{
				name: 'first_aid',
				photo: './assets/img/dpolg/card_img/erste_hilfe.png',
				uid: 'first_aid',
				url: '/pages/first_aid',
				usePhotoAsBackground: true,
			},
			{
				name: 'dpolg_gift_shop',
				photo: './assets/img/dpolg/card_img/vorteilswelt.png',
				uid: 'dpolg_gift_shop',
				url: 'https://www.dbb-vorteilswelt.de/',
				usePhotoAsBackground: true,
			},
			{
				name: 'job_exchange',
				photo: './assets/img/dpolg/card_img/stellentausch.png',
				uid: 'job_exchange',
				url: 'http://dpolg-bpolg.de/tauschboerse/',
				usePhotoAsBackground: true,
			},
			{
				name: 'driving_licence',
				photo: './assets/img/dpolg/card_img/fahrerlaubnis.png',
				uid: 'driving_licence',
				url: '/pages/driving_licence',
				usePhotoAsBackground: true,
			},
			{
				name: 'main_inspection',
				photo: './assets/img/dpolg/card_img/hu.png',
				uid: 'main_inspection',
				url: '/pages/main_inspection',
				usePhotoAsBackground: true,
			},
			{
				name: 'become_a_member',
				photo: './assets/img/dpolg/card_img/mitglied_werden.png',
				//photo: './assets/img/dpolg/card_img/heilfuersorge.png',
				uid: 'become_a_member',
				url: 'https://www.dpolg-bundespolizei.de/mitgliedschaft/online-beitritt/',
				usePhotoAsBackground: true,
			},
			// ,
			// {
			//   name: 'feedback',
			//   photo: './assets/img/dpolg/card_img/feedback.png',
			//   uid: 'feedback',
			//   url: 'https://forms.office.com/e/Px7MT72TWX',
			//   usePhotoAsBackground: true,
			// },
		],
	},
	links: {
		imprint: 'https://www.dpolg-markt-select.de/l/contact',
		privacy_policy: 'https://www.dpolg-markt-select.de/l/privacy',
		terms_of_use: 'https://www.dpolg-markt-select.de/l/tac',
	},
	loginHeadlineText: 'Willkommen in der DPolG App',
	maxPostAge: 365,
	SideDesktop: 'start',
	menuSideMobile: 'start',
	multiLanguageSupport: true,
	multiUser: true,
	orderBy: {
		discover: 'post_date_gmt desc',
		home: 'post_date_gmt desc',
		local: 'post_date_gmt desc',
		people: 'RAND()',
		shop: 'name',
		showroom: 'post_date_gmt desc',
	},
	postsVipFactor: 0,
	pushAppId: 'ac05c119-5059-4f81-b614-7ea965c62afa',
	routes: {
		discover: '/tabs/feed/31',
		//groups: '/page/groups',
		home: '/page/launcher',
		local: '/page/local',
		people: '/page/people',
		shop: '/page/shop',
	},
	showAccountBecomeCreator: false,
	showAccountClearCaches: false,
	showAccountSecurity: true,
	showAppearanceColorSchemes: true,
	showAppearanceFontsSelector: false,
	showAppearanceFontSizeSelector: false,
	showAppearancePreferedImageSize: false,
	showAppearanceTabs: false,
	showCheckoutPage: false,
	showCompaniesOnSearchPage: false,
	showEventsOnSearchPage: false,
	showFeedBottomShadow: false,
	showFooterAppVersion: false,
	showFooterBottomText: true,
	showGroupsOnSearchPage: true,
	showHeaderLargeTitle: true,
	showHeaderMenuButton: true,
	showHeaderToolbarLogo: true,
	showHeaderToolbarLogoInWeb: true,
	showHeaderToolbarLogoInApp: true,
	showHeaderToolbarTitle: false,
	showJobPostsInFeeds: false,
	showJobPostsInSearchResults: false,
	showJobPostsOnSearchPage: false,
	showLocalOnSearchPage: false,
	showLocalSourcesSuggestions: false,
	showLoginCredentialsSkipAccount: false,
	showLoginPage: false,
	showLoginPageLeftImg: true,
	showLoginTopLogo: true,
	showMenuGlobalSearch: true,
	showMenuHeaderLogo: true,
	showMenuHeaderTitle: false,
	showMenuIfLoggedOut: false,
	showMenuPagesInApp: true,
	showMenuPagesInWeb: true,
	showMoviesSuggestionsOnDiscoverPage: false,
	showMoviesSuggestionsOnFeedPage: false,
	showMoviesSuggestionsOnHomePage: false,
	showPeopleOnSearchPage: false,
	showPodcastsSuggestions: false,
	showPodcastsSuggestionsInFeed: false,
	showPostAuthorCard: false,
	showPostCardAdminFab: false,
	showPostCardExcerpt: true,
	showPostCardHostLabel: false,
	showPostCardOptions: false,
	showPostCardVerifiedBadges: false,
	showPostPagination: false,
	showPostReadInAppCard: false,
	showPostRelatedArticles: true,
	showPostsOnSearchPage: true,
	showProfileDisplayName: true,
	showProfileEvents: false,
	showProfileFriends: false,
	showProfileGroups: true,
	showProfilePosts: false,
	showProfileProducts: false,
	showProfileSocialInformation: true,
	showProfileSocialInformationLabels: true,
	showProfileUserGroup: true,
	showProfileUserGroupAsPrimaryLabel: true,
	showProfileUsername: false,
	showRegisterProjectSettings: false,
	showRegisterVideos: false,
	showSalut: true,
	showSettingsLegalLinks: true,
	showSettingsLinks: false,
	showShopCategories: true,
	showShopNewestProducts: true,
	showShopProductsOnSearchPage: true,
	showShopRelatedProductsOnDetailPage: true,
	showShopSaleProducts: true,
	showShopSources: false,
	showShopSuggestedProducts: true,
	showShopTrendingProducts: true,
	showSuggestedProfilesOnFeedPage: false,
	showSuggestedProfilesOnHomePage: false,
	showSuggestedProfilesOnLocalPage: false,
	showTabBar: true,
	showTabBarAsDock: false,
	showTabBarInMenuOnApp: true,
	showTabBarInMenuOnWeb: true,
	showTabBarLabels: true,
	showTabMenu: false,
	tabBarActiveStyle: 'solid',
	tabs: [
		{
			uid: 'launcher',
			checked: true,
			icon: 'home-outline',
			indent: 'launcher',
			index: 0,
			name: 'home',
			route: '/tabs/launcher',
			url: '/tabs/launcher',
		},
		{
			uid: 'feed_home',
			checked: true,
			icon: 'newspaper-outline',
			indent: 'feed_home',
			index: 0,
			name: 'news',
			route: '/tabs/feed/32',
			url: '/tabs/feed/32',
		},
		{
			uid: 'events_list',
			checked: true,
			icon: 'calendar-number-outline',
			indent: 'events_list',
			index: 1,
			name: 'calendar',
			route: '/tabs/dpolg/calendar',
			url: '/tabs/dpolg/calendar',
		},
		{
			uid: 'shop',
			checked: true,
			icon: 'storefront-outline',
			indent: 'shop',
			index: 3,
			name: 'shop',
			route: '/tabs/shop',
			url: '/tabs/shop',
		},
	],
	translucentFooters: false,
	translucentHeaders: false,
	useAbonnements: false,
	useAdsExtension: false,
	useAiExtension: true,
	useAppearance: true,
	useAppleWatchExtension: false,
	useArchive: false,
	useAssetsExtension: true,
	useAuthExtension: false,
	useAvatars: false,
	useBionicReadingExtension: false,
	useBlogsExtension: true,
	useCalendar: true,
	useCategories: false,
	useCategoriesOnDiscoverPage: false,
	useCategoriesOnFeedPages: false,
	useCategoriesOnHomePage: false,
	useCategoriesOnLocalPage: false,
	useCategoriesOnSearchPage: false,
	useChatExtension: false,
	useCollectionsExtension: false,
	useCompaniesExtension: false,
	useCommentsExtension: false,
	useComplexityExtension: false,
	useCookiesAlertInApp: false,
	useCookiesAlertInWebApp: false,
	useCouponsExtension: false,
	useCreativesExtension: true,
	useDatingExtension: false,
	useDeathAnnouncementsExtension: false,
	useDiscover: false,
	useDocumentsExtension: false,
	useEventsList: true,
	useExperiments: false,
	useFeedback: false,
	useFeeds: false,
	useFiltersExtension: false,
	useFollow: false,
	useGoogleMapsExtension: true,
	useGroups: false,
	useHeadlineProfileAvatar: false,
	useHelpCenterExtension: false,
	useHome: false,
	useInbox: false,
	useInterests: false,
	useIntro: false,
	useIntroCards: true,
	useIntroPeople: false,
	useIntroReadingSettings: false,
	useInviteFriends: false,
	useJobPosts: false,
	useJobTitlesExtension: true,
	useLocal: false,
	useLoomaExtension: false,
	useMarketplaceExtension: false,
	useMediaExtension: true,
	useMoviesExtension: false,
	useOrderByFilters: false,
	usePayPalExtension: false,
	usePeople: false,
	usePointsSystem: false,
	usePostPaywallExtension: false,
	usePostsAdmin: false,
	useProfile: false,
	useProfileDisplayNames: true,
	useProfileTitleExtension: true,
	useProfileUsernames: false,
	useProjectsExtension: false,
	usePushNotifications: true,
	usePushNotificationsChannels: false,
	useQuizExtension: false,
	useReactions: false,
	useRegionSearch: false,
	useRegionSearchSuggestions: false,
	useReportingExtension: true,
	userPostContentSettings: {
		active: true,
		external: false,
		category: 'feed',
		language: 'de',
		local: false,
		type: 'post',
		verified: true,
	},
	useSearch: false,
	useSettings: false,
	useSharingExtension: true,
	useShop: true,
	useShopAccount: false,
	useShopCategories: false,
	useShopInternalPaymentProcess: false,
	useShortcuts: false,
	useShowroom: false,
	useSignInWithApple: false,
	useSignInWithFacebook: false,
	useSignInWithGoogle: false,
	useSimplyLocalExtension: false,
	useStatisticsExtension: true,
	useStories: false,
	useStoriesCameraExtension: false,
	useStoriesOnDiscoverPage: false,
	useStoriesOnHomePage: false,
	useStoriesOnLocalPage: false,
	useStoriesOnPeoplePage: false,
	useSurveyExtension: true,
	useTeamsExtension: true,
	useTesting: false,
	useThemes: true,
	useThreeDeeTouch: false,
	useTransparencyExtension: false,
	useTvExtension: false,
	useVideosExtension: false,
	useWallet: false,
	useWebsitesExtension: false,
	useWeclappExtension: false,
	useWeloveWalletExtension: false,
};
